# Generated by Django 4.0.5 on 2022-07-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_featured',
            field=models.BooleanField(default=0),
        ),
    ]
