# Generated by Django 4.0.5 on 2022-07-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_post_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_featured',
            new_name='featured',
        ),
    ]
