# Generated by Django 4.0.5 on 2022-07-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_post_featured_blogpost_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.TextField(max_length=100)),
                ('contact_email', models.EmailField(max_length=100)),
                ('contact_subject', models.TextField(max_length=100)),
                ('contact_msg', models.CharField(max_length=1000)),
                ('contact_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
