# Generated by Django 4.0.5 on 2022-07-05 11:28

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_slug',
            field=models.SlugField(max_length=200, null=sqlalchemy.sql.expression.true, unique=True),
        ),
    ]
