# Generated by Django 4.0.5 on 2022-07-05 11:57

import autoslug.fields
from django.db import migrations
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=sqlalchemy.sql.expression.true, populate_from='post_title', unique=True),
        ),
    ]
